apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: diffusers-v2
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/diffusers:v2
        resources:
          limits:
            cpu: "12"
            memory: 24Gi
          requests:
            cpu: "12"
            memory: 24Gi
    timeout: 300