apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sentiment-analysis
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/sentiment-analysis:latest
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "2"
            memory: 2Gi
    timeout: 300