apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: languages-51
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/languages-51:latest
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: "2"
            memory: 3Gi
    timeout: 300