apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fr-en
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/fr-en:latest
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
    timeout: 300