apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: de-en
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/de-en:latest
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
    timeout: 300