apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: xlm-roberta-base-language-detection
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/xlm-roberta-base-language-detection:latest
        resources:
          limits:
            cpu: "2"
            memory: 3Gi
          requests:
            cpu: "2"
            memory: 3Gi
    timeout: 300