apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: es-en
spec:
  predictor:
    containers:
      - name: kserve-container
        image: lasylphide/es-en:latest
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
    timeout: 300