apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph
metadata:
  name: ensemble
spec:
  nodes:
    root:
      routerType: Ensemble
      steps:
      - serviceName: languages-51
        name: languages-51
      - serviceName: lingua
        name: lingua
      - serviceName: xlm-roberta-base-language-detection
        name: xlm-roberta-base-language-detection
