apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph
metadata:
  name: ensemble
spec:
  nodes:
    ensembleModel:
      routerType: Ensemble
      routes:
      - service: languages-51
      - service: lingua
      - service: xlm-roberta-base-language-detection