apiVersion: "serving.kserve.io/v1alpha1"
kind: InferenceGraph
metadata:
  name: switch
spec:
  nodes:
    root:
      routerType: Switch
      steps:
      - serviceName: de-en
        condition: "[@this].#(instances.0==\"de\")"
      - serviceName: es-en
        condition: "[@this].#(instances.0==\"es\")"
      - serviceName: fr-en
        condition: "[@this].#(instances.0==\"fr\")"
      - serviceName: zh-en
        condition: "[@this].#(instances.0==\"zh\")"
      - serviceName: ru-en
        condition: "[@this].#(instances.0==\"ru\")"